wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.10
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694203784.485583
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      - 71
      - 83
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      - 71
      - 83
      3:
      - 23
      4: 3.10.12
      5: 0.15.10
      6: 4.31.0
      8:
      - 5
